apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: receipts-pvc
  namespace: booking-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
