apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: booking-app
  namespace: booking-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: booking-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
